// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded for Vercel override debugging
const SUPABASE_URL = "https://suffvdkcwwpdacrxnccm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_Hkggl9c_5OYPuoUVSkDtNA_lyUD8FvG";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});